# Generated by Django 3.0.7 on 2020-06-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('foundation', models.PositiveIntegerField()),
                ('championship', models.PositiveIntegerField()),
                ('history', models.TextField(blank=True, null=True)),
                ('founders', models.CharField(max_length=300)),
                ('followers', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
