# Generated by Django 3.0.7 on 2020-06-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bornplace', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('biography', models.TextField(blank=True, null=True)),
                ('team', models.CharField(max_length=300)),
                ('championship', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
